{% set name = "xagg" %}
{% set version = "0.3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xagg-{{ version }}.tar.gz
  sha256: 40c9a7308af4b287029b6aa06f80d629b287d235c4f6aaca5620d88566219d0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - xarray
    - pandas
    - netcdf4
    - geopandas >=0.12.0
    - shapely
    - pytables
    - cf_xarray >=0.5.1
    - requests

test:
  imports:
    - xagg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ks905383/xagg
  summary: Aggregating raster data over polygons
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ks905383
